name: ci

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with: { version: 8 }

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      # build
      #

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
