name: ci

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  push-to-dist-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: apt install
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: jq

      - uses: pnpm/action-setup@v2
        with: { version: 8 }

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      # build
      - run: pnpm build

      # plugin-dist
      - name: prepare publish
        run: |
          mkdir to-dist-repo
          cp -R ./src-plugin/dist ./to-dist-repo
          cp ./src-plugin/Info.json ./to-dist-repo
          cp ./README.md ./to-dist-repo
          cat ./package.json | jq 'del(.devDependencies)' > ./to-dist-repo/package.json

      # cp ./src-plugin/package.json ./to-dist-repo
      - name: Deploy(commit to -dist repo)
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: magicdawn/iina-plugin-thunder-subtitle-dist
          publish_branch: main # default: gh-pages
          publish_dir: ./to-dist-repo
          force_orphan: true
